export const TODO_FETCH = 'TODO_FETCH';
export const TODO_FETCH_START = 'TODO_FETCH_START';
export const TODO_FETCH_SUCCESS = 'TODO_FETCH_SUCCESS';
export const TODO_FETCH_FAIL = 'TODO_FETCH_FAIL';

export const TODO_UPDATE = 'TODO_UPDATE';
export const TODO_UPDATE_START = 'TODO_UPDATE_START';
export const TODO_UPDATE_SUCCESS = 'TODO_UPDATE_SUCCESS';
export const TODO_UPDATE_FAIL = 'TODO_UPDATE_FAIL';

export const TODO_DELETE = 'TODO_DELETE';
export const TODO_DELETE_START = 'TODO_DELETE_START';
export const TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS';
export const TODO_DELETE_FAIL = 'TODO_DELETE_FAIL';

export const TODO_SEARCH = 'TODO_SEARCH';
export const TODO_SEARCH_START = 'TODO_SEARCH_START';
export const TODO_SEARCH_SUCCESS = 'TODO_SEARCH_SUCCESS';
export const TODO_SEARCH_FAIL = 'TODO_SEARCH_FAIL';
